name: "Auto Create & Assign Labels"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Labels and colors
          LABELS=("Level 1 / Beginner:#7AE7FF" "Level 2 / Intermediate:#FFAB70" "Level 3 / Advanced:#FF7F7F" "GSSoC 25:#6F42C1")

          for label_pair in "${LABELS[@]}"; do
            NAME="${label_pair%%:*}"
            COLOR="${label_pair##*:}"
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/labels \
              -d "{\"name\":\"$NAME\",\"color\":\"$COLOR\"}")
            if [ "$STATUS" = "422" ]; then
              echo "Label '$NAME' already exists."
            else
              echo "Label '$NAME' created."
            fi
          done

          # Detect if it's a PR or Issue
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            NUMBER=${{ github.event.pull_request.number }}
            TITLE="${{ github.event.pull_request.title }}"
            BODY="${{ github.event.pull_request.body }}"
          else
            NUMBER=${{ github.event.issue.number }}
            TITLE="${{ github.event.issue.title }}"
            BODY="${{ github.event.issue.body }}"
          fi

          TEXT="$TITLE $BODY"

          # Advanced scoring based on keywords
          SCORE=0
          # Level 1
          echo "$TEXT" | grep -iqE "typo|doc|documentation|readme|ui" && SCORE=$((SCORE+1))
          # Level 2
          echo "$TEXT" | grep -iqE "feature|bug|small|update|fix" && SCORE=$((SCORE+2))
          # Level 3
          echo "$TEXT" | grep -iqE "major|refactor|performance|optimization|critical" && SCORE=$((SCORE+3))

          # Determine level label
          if [ $SCORE -le 2 ]; then
            LEVEL_LABEL="Level 1 / Beginner"
          elif [ $SCORE -le 4 ]; then
            LEVEL_LABEL="Level 2 / Intermediate"
          else
            LEVEL_LABEL="Level 3 / Advanced"
          fi

          # Assign labels
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$NUMBER/labels \
            -d "{\"labels\":[\"GSSoC 25\",\"$LEVEL_LABEL\"]}"

          echo "Assigned Labels: GSSoC 25, $LEVEL_LABEL"
