name: Auto Comment on Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  test-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const opener = context.payload.issue.user.login;

            const commentBody1 = `### Thank you for raising this issue, @${opener}!
We'll review it as soon as possible. We truly appreciate your contributions! ✨

> Meanwhile, make sure you've visited the README.md, CONTRIBUTING.md, and CODE_OF_CONDUCT.md before creating a PR for this. Also, please do NOT create a PR until this issue has been assigned to you. 😊`;

            const commentBody2 = `Just a friendly reminder: cc @maintainer1 @maintainer2 for visibility.`; // Optional second comment, replace with actual usernames

            // First comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody1
            });

            // Second comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody2
            });

            console.log('Both comments added successfully.');
