name: Test Comment on Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  test-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Full payload:", JSON.stringify(context.payload));
            const issueNumber = context.issue.number;
            console.log("Issue number:", issueNumber);
            const opener = context.payload.issue.user.login;
            console.log("Issue opened by:", opener);

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `Hello @${opener}, this is a test comment!`
            });
